### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by ki7** [ki7/gerimmo-netlify#1]
# TODO Moi
- [ ] Toit moins épais
- [ ] fenetre moin haute
- [ ] Sortir gerimmo du Logo
- [ ] Fond beige pour les pages

- [ ] Revoir le showcase dans le modele Wix plus petit
  - [ ] Rectangle comme wix
  - [ ] plus fin comm ing

#  TODO Gersande
- [ ] choix du design du formulaire?
- [ ] Categorie chois des images.
